### ISSUE TITLE
Mocha now has a built-in retry feature - maybe mention it in the readme

### ISSUE THREAD

**Issue by nfriedly** [giggio/mocha-retry#10]
See http://mochajs.org/#retry-tests

I'd recommend adding a line like this to the top of the readme and putting out a patch release:

> **Notice:** This library is deprecated. Automatic retries are now a built-in feature of Mocha via `this.retries(num)`, and we recommend that you use that instead. See [Mocha's documentation](http://mochajs.org/#retry-tests) for more details. 
> 
> The `mocha-retry` library will remain as-is to support existing users, but it will not see any further updates.

**Comment by giggio** [comment]
This is a good idea, a PR to show a warning on install is welcome. I will update the readme.

**Comment by nfriedly** [comment]
Op, I started a private, but it looks like you beat me to it.
