### ISSUE TITLE
GPL license?

### ISSUE THREAD

**Issue by adamgauthier** [giggio/mocha-retry#7]
Hi,

Thanks for this library, but I have a concern:

Is there a reason why this package is licensed GPL? The vast majority of the Node packages are MIT and using GPL has several downsides in a commercial context.

If you do not have a strong opinion on licenses, I suggest you consider [MIT](http://opensource.org/licenses/MIT) or [Apache](http://opensource.org/licenses/Apache-2.0).

You can also see this discussion about licenses for NodeJS modules: https://groups.google.com/forum/#!topic/nodejs/5xxD2c4UfK8

**Comment by giggio** [comment]
I've been using Apache2 on most of my recent work. Send a PR and I will accept it.

**Comment by adamgauthier** [comment]
Excellent, thank you!
